version: "3.8"
x-common-db-options:
  environment:
    &db_env
      POSTGRES_USER: vote
      POSTGRES_PASSWORD: String-password-for-DB
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_DB: vote-db

services:
  proxy:
    build:
      context: ./proxy
      dockerfile: Dockerfile
    command: --configfile=/etc/traefik/static.yml
    environment:
      - DOMAIN=localhost
      - TRAEFIK_DOMAIN=localhost
      - DASHBOARD_PASSWORD=osayd:$$apr1$$ZvG8aqL3$$sVd4d.CMnjQCePNmnOP9W.
    volumes:
      - ./proxy/configs:/etc/traefik/configs
      - certificates-data:/etc/traefik/acme/
    ports:
      - "80:80"
      - "443:443"
    restart: always
    networks:
      - proxy_nw

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        - INSTALL_DEV=true
    entrypoint: /backend/scripts/run_backend.sh
    # entrypoint: bash -c
    environment:
      << : *db_env
      ENV: ${ENV:-development}
      BACKEND_PORT: 8916
      BACKEND_LOG_LEVEL: debug
    expose:
      - "8916"
    restart: always
    networks:
      - proxy_nw
      - db_nw

  db:
    image: postgres:14.5
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      <<: *db_env
    expose:
      - "5432"
    ports:
      - "5432:5432"
    restart: always
    networks:
      - db_nw

networks:
  proxy_nw:
  db_nw:

volumes:
  db-data:
  certificates-data:
