name: Clean up killed bot

on:
  pull_request:
    types: [ closed ]

jobs:
  garbage-collection:
    runs-on: [self-hosted]
    # run if the closed pull request is from a branch that starts with 'deploy-bot'
    if: ${{ startsWith(github.event.pull_request.head.ref, 'deploy-bot') && ! github.event.pull_request.merged }}
    steps:
    - name: Change file permissions
      run: |
        sudo chown -R $USER:$USER $PWD
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Get version that bot deleted and ECR_REPO
      run: |
        echo "BOT_VERSION=$(git describe --abbrev=0)" >> $GITHUB_ENV
    - name: Delete New Version Tag that Bot created
      run: |
        git push origin --delete ${{ env.BOT_VERSION }}
